#!/bin/bash

# Takes argument as connection to connect to, and optional password.
# Nothing happens if password is left blank if the connection doesn't 
# require one.

if [[ $2 != "" ]]; then
	pass="password $2"
fi

nmcli dev wifi connect $1 $pass
